-- 供應商資料表
CREATE TABLE IF NOT EXISTS suppliers (
  sup_id TEXT PRIMARY KEY,
  supplier_code TEXT,
  name TEXT NOT NULL DEFAULT '',
  contact_name TEXT DEFAULT '',
  responsible_person TEXT DEFAULT '',
  email TEXT DEFAULT '',
  payment_terms TEXT DEFAULT '',
  phone1 TEXT DEFAULT '',
  phone2 TEXT DEFAULT '',
  mobile TEXT DEFAULT '',
  fax TEXT DEFAULT '',
  tax_id TEXT DEFAULT '',
  invoice_title TEXT DEFAULT '',
  invoice_address TEXT DEFAULT '',
  zip_code TEXT DEFAULT '',
  website TEXT DEFAULT '',
  closing_day TEXT DEFAULT '',
  region_code TEXT DEFAULT '',
  accounting_code TEXT DEFAULT '',
  address TEXT DEFAULT '',
  country TEXT DEFAULT 'Taiwan',
  currency TEXT DEFAULT 'TWD',
  categories TEXT DEFAULT '[]',
  rating REAL DEFAULT 0,
  notes TEXT DEFAULT '',
  tier TEXT DEFAULT 'B',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 客戶資料表
CREATE TABLE IF NOT EXISTS customers (
  cust_id TEXT PRIMARY KEY,
  customer_code TEXT,
  name TEXT NOT NULL DEFAULT '',
  contact_name TEXT DEFAULT '',
  responsible_person TEXT DEFAULT '',
  email TEXT DEFAULT '',
  payment_terms TEXT DEFAULT '',
  phone1 TEXT DEFAULT '',
  phone2 TEXT DEFAULT '',
  mobile TEXT DEFAULT '',
  fax TEXT DEFAULT '',
  tax_id TEXT DEFAULT '',
  invoice_title TEXT DEFAULT '',
  invoice_address TEXT DEFAULT '',
  zip_code TEXT DEFAULT '',
  website TEXT DEFAULT '',
  closing_day TEXT DEFAULT '',
  collection_day TEXT DEFAULT '',
  region_code TEXT DEFAULT '',
  accounting_code TEXT DEFAULT '',
  address TEXT DEFAULT '',
  delivery_address TEXT DEFAULT '',
  salesperson TEXT DEFAULT '',
  full_invoice INTEGER DEFAULT 0,
  country TEXT DEFAULT 'Taiwan',
  currency TEXT DEFAULT 'TWD',
  tier TEXT DEFAULT 'B',
  credit_limit REAL DEFAULT 0,
  notes TEXT DEFAULT '',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
